# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Website/blog info
title: Alzheimer's Proof Vault
subtitle: Great Things Never Come From Comfort Zones # website subtitle
description: Software Engineer # website description for SEO purposes
keywords: Machine Learning,Data Analysis,Software Architecture,Cybersecurity # keywords for SEO purposes?
author: L
language: en-US
timezone: Europe/Madrid

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ryuzakyl.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source # Resource folder, this folder is used to store content
public_dir: public # Public folder, this folder is used to store the generated site files
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# https://theme-next.iissnan.com/third-party-services.html#local-search
# Local search, install the plugin in the root directory of the site：
#   npm install hexo-generator-searchdb --save
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
# Symbol count and time to read articles
# npm install hexo-symbols-count-time --save
# https://blog.runningcoder.me/2018/04/26/create-personal-blog-with-github-and-hexo-V/
symbols_count_time:
  symbols: true       # Number of characters
  time: true          # Reading time of this article
  total_symbols: true # Total words on site
  total_time: true    # Total reading time of the site

# seo优化 https://hoxis.github.io/Hexo+Next%20SEO%E4%BC%98%E5%8C%96.html
# npm install hexo-generator-sitemap --save
# npm install hexo-generator-baidu-sitemap --save
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# https://github.com/huiwang/hexo-baidu-url-submit
# npm install hexo-baidu-url-submit --save
baidu_url_submit:
  count: 1000 ## Submit the latest link
  host: https://ryuzakyl.github.io/ ## Domain name registered in Baidu webmaster platform
  token:  ## Please note that this is your secret key, so please do not publish the blog source code in the public repository!
  path: baidu_urls.txt ## The address of the text document, the new link will be saved in this text document

# douban:
#   user: 51517255
#   builtin: true
#   book:
#     title: '阅读'
#     quote: '书读百遍，其义自见'
#   movie:
#     title: '观影'
#     quote: <div class="note success no-icon"><p>You got a dream, you gotta protect it. People can't do something themselves, they wanna tell you you can't do it.If you want something, go get it. --《当幸福来敲门》</p></div>
#   # game:
#   #   title: 'This is my game title'
#   #   quote: 'This is my game quote'
#   timeout: 10000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
## npm install hexo-deployer-git --save
deploy:
- type: git
  # The gh_token below will be replaced by the sed command in .travis.yml
  repo: https://github_token@github.com/ryuzakyl/ryuzakyl.github.io.git
  branch: master

- type: baidu_url_submitter

emoji:
  enable: true
  className: github-emoji
  styles:
  customEmojis:

filter_optimize:
  enable: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: false
  css:
    # minify all css files
    minify: true
    # bundle loaded css files into one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
  js:
    # minify all js files
    minify: true
    # bundle loaded js files into one
    bundle: true
    excludes:
  # set the priority of this plugin,
  # lower means it will be executed first, default of Hexo is 10
  priority: 12

# enable hexo server cache
server:
  cache: true